---
dependency:
  name: galaxy

driver:
  name: podman

platforms:
  - name: ubuntu
    image: docker.io/geerlingguy/docker-ubuntu2404-ansible
    pre_build_image: true
    privileged: true
    dns_servers:
      - 8.8.8.8

provisioner:
  name: ansible

verifier:
  name: ansible
